// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package jv

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"golang.org/x/text/encoding/japanese"
	"strconv"
)

type JvRaRace struct {
	Records *JvRaRace_Record
	_io *kaitai.Stream
	_root *JvRaRace
	_parent interface{}
}
func NewJvRaRace() *JvRaRace {
	return &JvRaRace{
	}
}

func (this *JvRaRace) Read(io *kaitai.Stream, parent interface{}, root *JvRaRace) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewJvRaRace_Record()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Records = tmp1
	return err
}
type JvRaRace_RaceId struct {
	Year string
	Month string
	Day string
	JyoCode string
	Kaiji string
	Nichiji string
	RaceNum string
	_io *kaitai.Stream
	_root *JvRaRace
	_parent *JvRaRace_Record
}
func NewJvRaRace_RaceId() *JvRaRace_RaceId {
	return &JvRaRace_RaceId{
	}
}

func (this *JvRaRace_RaceId) Read(io *kaitai.Stream, parent *JvRaRace_Record, root *JvRaRace) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	tmp3, err := kaitai.BytesToStr(tmp2, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Year = tmp3
	tmp4, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp4 = tmp4
	tmp5, err := kaitai.BytesToStr(tmp4, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Month = tmp5
	tmp6, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	tmp7, err := kaitai.BytesToStr(tmp6, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Day = tmp7
	tmp8, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp8 = tmp8
	tmp9, err := kaitai.BytesToStr(tmp8, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyoCode = tmp9
	tmp10, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp10 = tmp10
	tmp11, err := kaitai.BytesToStr(tmp10, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Kaiji = tmp11
	tmp12, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp12 = tmp12
	tmp13, err := kaitai.BytesToStr(tmp12, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Nichiji = tmp13
	tmp14, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp14 = tmp14
	tmp15, err := kaitai.BytesToStr(tmp14, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.RaceNum = tmp15
	return err
}
type JvRaRace_Result struct {
	LapTimeStrs []string
	SyogaiMileTime string
	HaronTimeS3Str string
	HaronTimeS4Str string
	HaronTimeL3Str string
	HaronTimeL4Str string
	Corner1 string
	Syukaisu1 string
	Jyuni1 string
	Corner2 string
	Syukaisu2 string
	Jyuni2 string
	Corner3 string
	Syukaisu3 string
	Jyuni3 string
	Corner4Str string
	Syukaisu4Str string
	Jyuni4 string
	RecordUpKubun []byte
	Crlf []byte
	_io *kaitai.Stream
	_root *JvRaRace
	_parent *JvRaRace_Record
	_f_haronTimeS4 bool
	haronTimeS4 int
	_f_lapTimes bool
	lapTimes []*JvRaRace_LapTime
	_f_haronTimeS3 bool
	haronTimeS3 int
	_f_haronTimeL3 bool
	haronTimeL3 int
	_f_haronTimeL4 bool
	haronTimeL4 int
}
func NewJvRaRace_Result() *JvRaRace_Result {
	return &JvRaRace_Result{
	}
}

func (this *JvRaRace_Result) Read(io *kaitai.Stream, parent *JvRaRace_Record, root *JvRaRace) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(25); i++ {
		_ = i
		tmp16, err := this._io.ReadBytes(int(3))
		if err != nil {
			return err
		}
		tmp16 = tmp16
		tmp17, err := kaitai.BytesToStr(tmp16, japanese.ShiftJIS.NewDecoder())
		if err != nil {
			return err
		}
		this.LapTimeStrs = append(this.LapTimeStrs, tmp17)
	}
	tmp18, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp18 = tmp18
	tmp19, err := kaitai.BytesToStr(tmp18, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.SyogaiMileTime = tmp19
	tmp20, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp20 = tmp20
	tmp21, err := kaitai.BytesToStr(tmp20, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HaronTimeS3Str = tmp21
	tmp22, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp22 = tmp22
	tmp23, err := kaitai.BytesToStr(tmp22, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HaronTimeS4Str = tmp23
	tmp24, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp24 = tmp24
	tmp25, err := kaitai.BytesToStr(tmp24, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HaronTimeL3Str = tmp25
	tmp26, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp26 = tmp26
	tmp27, err := kaitai.BytesToStr(tmp26, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HaronTimeL4Str = tmp27
	tmp28, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp28 = tmp28
	tmp29, err := kaitai.BytesToStr(tmp28, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Corner1 = tmp29
	tmp30, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp30 = tmp30
	tmp31, err := kaitai.BytesToStr(tmp30, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Syukaisu1 = tmp31
	tmp32, err := this._io.ReadBytes(int(70))
	if err != nil {
		return err
	}
	tmp32 = tmp32
	tmp33, err := kaitai.BytesToStr(tmp32, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Jyuni1 = tmp33
	tmp34, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp34 = tmp34
	tmp35, err := kaitai.BytesToStr(tmp34, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Corner2 = tmp35
	tmp36, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp36 = tmp36
	tmp37, err := kaitai.BytesToStr(tmp36, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Syukaisu2 = tmp37
	tmp38, err := this._io.ReadBytes(int(70))
	if err != nil {
		return err
	}
	tmp38 = tmp38
	tmp39, err := kaitai.BytesToStr(tmp38, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Jyuni2 = tmp39
	tmp40, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp40 = tmp40
	tmp41, err := kaitai.BytesToStr(tmp40, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Corner3 = tmp41
	tmp42, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp42 = tmp42
	tmp43, err := kaitai.BytesToStr(tmp42, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Syukaisu3 = tmp43
	tmp44, err := this._io.ReadBytes(int(70))
	if err != nil {
		return err
	}
	tmp44 = tmp44
	tmp45, err := kaitai.BytesToStr(tmp44, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Jyuni3 = tmp45
	tmp46, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp46 = tmp46
	tmp47, err := kaitai.BytesToStr(tmp46, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Corner4Str = tmp47
	tmp48, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp48 = tmp48
	tmp49, err := kaitai.BytesToStr(tmp48, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Syukaisu4Str = tmp49
	tmp50, err := this._io.ReadBytes(int(70))
	if err != nil {
		return err
	}
	tmp50 = tmp50
	tmp51, err := kaitai.BytesToStr(tmp50, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Jyuni4 = tmp51
	tmp52, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp52 = tmp52
	this.RecordUpKubun = tmp52
	tmp53, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp53 = tmp53
	this.Crlf = tmp53
	return err
}
func (this *JvRaRace_Result) HaronTimeS4() (v int, err error) {
	if (this._f_haronTimeS4) {
		return this.haronTimeS4, nil
	}
	tmp54, err := strconv.ParseInt(this.HaronTimeS4Str, 10, 0)
	if err != nil {
		return 0, err
	}
	this.haronTimeS4 = int(tmp54)
	this._f_haronTimeS4 = true
	return this.haronTimeS4, nil
}
func (this *JvRaRace_Result) LapTimes() (v []*JvRaRace_LapTime, err error) {
	if (this._f_lapTimes) {
		return this.lapTimes, nil
	}
	for i := 0; i < int(25); i++ {
		_ = i
		tmp55 := NewJvRaRace_LapTime(int64(i))
		err = tmp55.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.lapTimes = append(this.lapTimes, tmp55)
	}
	this._f_lapTimes = true
	this._f_lapTimes = true
	return this.lapTimes, nil
}
func (this *JvRaRace_Result) HaronTimeS3() (v int, err error) {
	if (this._f_haronTimeS3) {
		return this.haronTimeS3, nil
	}
	tmp56, err := strconv.ParseInt(this.HaronTimeS3Str, 10, 0)
	if err != nil {
		return 0, err
	}
	this.haronTimeS3 = int(tmp56)
	this._f_haronTimeS3 = true
	return this.haronTimeS3, nil
}
func (this *JvRaRace_Result) HaronTimeL3() (v int, err error) {
	if (this._f_haronTimeL3) {
		return this.haronTimeL3, nil
	}
	tmp57, err := strconv.ParseInt(this.HaronTimeL3Str, 10, 0)
	if err != nil {
		return 0, err
	}
	this.haronTimeL3 = int(tmp57)
	this._f_haronTimeL3 = true
	return this.haronTimeL3, nil
}
func (this *JvRaRace_Result) HaronTimeL4() (v int, err error) {
	if (this._f_haronTimeL4) {
		return this.haronTimeL4, nil
	}
	tmp58, err := strconv.ParseInt(this.HaronTimeL4Str, 10, 0)
	if err != nil {
		return 0, err
	}
	this.haronTimeL4 = int(tmp58)
	this._f_haronTimeL4 = true
	return this.haronTimeL4, nil
}
type JvRaRace_LapTime struct {
	I int64
	_io *kaitai.Stream
	_root *JvRaRace
	_parent *JvRaRace_Result
	_f_value bool
	value int
}
func NewJvRaRace_LapTime(i int64) *JvRaRace_LapTime {
	return &JvRaRace_LapTime{
		I: i,
	}
}

func (this *JvRaRace_LapTime) Read(io *kaitai.Stream, parent *JvRaRace_Result, root *JvRaRace) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
func (this *JvRaRace_LapTime) Value() (v int, err error) {
	if (this._f_value) {
		return this.value, nil
	}
	tmp59, err := strconv.ParseInt(this._parent.LapTimeStrs[this.I], 10, 0)
	if err != nil {
		return 0, err
	}
	this.value = int(tmp59)
	this._f_value = true
	return this.value, nil
}
type JvRaRace_Record struct {
	RecordSpec string
	DataKubun string
	CreatedYear string
	CreatedMonth string
	CreatedDay string
	RaceId *JvRaRace_RaceId
	YoubiCode string
	TokuNum string
	Hondai string
	Fukudai string
	Kakko string
	HondaiEng string
	FukudaiEng string
	KakkoEng string
	Ryakusyo10 string
	Ryakusyo6 string
	Ryakusyo3 string
	Kubun string
	Nkai string
	GradeCode string
	GradeCodeBefore string
	SyubetuCode string
	KigoCode string
	JyuryoCode string
	JyokenCode2 string
	JyokenCode3 string
	JyokenCode4 string
	JyokenCode5YearsOldAndOver string
	JyokenCodeYoungest string
	JyokenName string
	KyoriStr string
	KyoriBeforeStr string
	TrackCode string
	TrackCodeBefore string
	CourseKubunCode string
	CourseKubunCodeBefore string
	Honsyokin []string
	HonsyokinBefore []string
	Fukasyokin []string
	FukasyokinBefore []string
	HassoTime string
	HassoTimeBefore string
	TorokuTosu string
	SyussoTosu string
	NyusenTosu string
	TenkoCode string
	SibaBabaCode string
	DirtBabaCode string
	Result *JvRaRace_Result
	_io *kaitai.Stream
	_root *JvRaRace
	_parent *JvRaRace
	_f_isResult bool
	isResult bool
	_f_kyori bool
	kyori int
	_f_kyoriBefore bool
	kyoriBefore int
}
func NewJvRaRace_Record() *JvRaRace_Record {
	return &JvRaRace_Record{
	}
}

func (this *JvRaRace_Record) Read(io *kaitai.Stream, parent *JvRaRace, root *JvRaRace) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp60, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp60 = tmp60
	tmp61, err := kaitai.BytesToStr(tmp60, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.RecordSpec = tmp61
	tmp62, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp62 = tmp62
	tmp63, err := kaitai.BytesToStr(tmp62, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.DataKubun = tmp63
	tmp64, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp64 = tmp64
	tmp65, err := kaitai.BytesToStr(tmp64, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.CreatedYear = tmp65
	tmp66, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp66 = tmp66
	tmp67, err := kaitai.BytesToStr(tmp66, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.CreatedMonth = tmp67
	tmp68, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp68 = tmp68
	tmp69, err := kaitai.BytesToStr(tmp68, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.CreatedDay = tmp69
	tmp70 := NewJvRaRace_RaceId()
	err = tmp70.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.RaceId = tmp70
	tmp71, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp71 = tmp71
	tmp72, err := kaitai.BytesToStr(tmp71, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.YoubiCode = tmp72
	tmp73, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp73 = tmp73
	tmp74, err := kaitai.BytesToStr(tmp73, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.TokuNum = tmp74
	tmp75, err := this._io.ReadBytes(int(60))
	if err != nil {
		return err
	}
	tmp75 = tmp75
	tmp76, err := kaitai.BytesToStr(tmp75, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Hondai = tmp76
	tmp77, err := this._io.ReadBytes(int(60))
	if err != nil {
		return err
	}
	tmp77 = tmp77
	tmp78, err := kaitai.BytesToStr(tmp77, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Fukudai = tmp78
	tmp79, err := this._io.ReadBytes(int(60))
	if err != nil {
		return err
	}
	tmp79 = tmp79
	tmp80, err := kaitai.BytesToStr(tmp79, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Kakko = tmp80
	tmp81, err := this._io.ReadBytes(int(120))
	if err != nil {
		return err
	}
	tmp81 = tmp81
	tmp82, err := kaitai.BytesToStr(tmp81, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HondaiEng = tmp82
	tmp83, err := this._io.ReadBytes(int(120))
	if err != nil {
		return err
	}
	tmp83 = tmp83
	tmp84, err := kaitai.BytesToStr(tmp83, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.FukudaiEng = tmp84
	tmp85, err := this._io.ReadBytes(int(120))
	if err != nil {
		return err
	}
	tmp85 = tmp85
	tmp86, err := kaitai.BytesToStr(tmp85, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.KakkoEng = tmp86
	tmp87, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp87 = tmp87
	tmp88, err := kaitai.BytesToStr(tmp87, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Ryakusyo10 = tmp88
	tmp89, err := this._io.ReadBytes(int(12))
	if err != nil {
		return err
	}
	tmp89 = tmp89
	tmp90, err := kaitai.BytesToStr(tmp89, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Ryakusyo6 = tmp90
	tmp91, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp91 = tmp91
	tmp92, err := kaitai.BytesToStr(tmp91, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Ryakusyo3 = tmp92
	tmp93, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp93 = tmp93
	tmp94, err := kaitai.BytesToStr(tmp93, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Kubun = tmp94
	tmp95, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp95 = tmp95
	tmp96, err := kaitai.BytesToStr(tmp95, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Nkai = tmp96
	tmp97, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp97 = tmp97
	tmp98, err := kaitai.BytesToStr(tmp97, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.GradeCode = tmp98
	tmp99, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp99 = tmp99
	tmp100, err := kaitai.BytesToStr(tmp99, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.GradeCodeBefore = tmp100
	tmp101, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp101 = tmp101
	tmp102, err := kaitai.BytesToStr(tmp101, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.SyubetuCode = tmp102
	tmp103, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp103 = tmp103
	tmp104, err := kaitai.BytesToStr(tmp103, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.KigoCode = tmp104
	tmp105, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp105 = tmp105
	tmp106, err := kaitai.BytesToStr(tmp105, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyuryoCode = tmp106
	tmp107, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp107 = tmp107
	tmp108, err := kaitai.BytesToStr(tmp107, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyokenCode2 = tmp108
	tmp109, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp109 = tmp109
	tmp110, err := kaitai.BytesToStr(tmp109, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyokenCode3 = tmp110
	tmp111, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp111 = tmp111
	tmp112, err := kaitai.BytesToStr(tmp111, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyokenCode4 = tmp112
	tmp113, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp113 = tmp113
	tmp114, err := kaitai.BytesToStr(tmp113, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyokenCode5YearsOldAndOver = tmp114
	tmp115, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp115 = tmp115
	tmp116, err := kaitai.BytesToStr(tmp115, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyokenCodeYoungest = tmp116
	tmp117, err := this._io.ReadBytes(int(60))
	if err != nil {
		return err
	}
	tmp117 = tmp117
	tmp118, err := kaitai.BytesToStr(tmp117, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.JyokenName = tmp118
	tmp119, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp119 = tmp119
	tmp120, err := kaitai.BytesToStr(tmp119, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.KyoriStr = tmp120
	tmp121, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp121 = tmp121
	tmp122, err := kaitai.BytesToStr(tmp121, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.KyoriBeforeStr = tmp122
	tmp123, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp123 = tmp123
	tmp124, err := kaitai.BytesToStr(tmp123, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.TrackCode = tmp124
	tmp125, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp125 = tmp125
	tmp126, err := kaitai.BytesToStr(tmp125, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.TrackCodeBefore = tmp126
	tmp127, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp127 = tmp127
	tmp128, err := kaitai.BytesToStr(tmp127, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.CourseKubunCode = tmp128
	tmp129, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp129 = tmp129
	tmp130, err := kaitai.BytesToStr(tmp129, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.CourseKubunCodeBefore = tmp130
	for i := 0; i < int(7); i++ {
		_ = i
		tmp131, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp131 = tmp131
		tmp132, err := kaitai.BytesToStr(tmp131, japanese.ShiftJIS.NewDecoder())
		if err != nil {
			return err
		}
		this.Honsyokin = append(this.Honsyokin, tmp132)
	}
	for i := 0; i < int(5); i++ {
		_ = i
		tmp133, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp133 = tmp133
		tmp134, err := kaitai.BytesToStr(tmp133, japanese.ShiftJIS.NewDecoder())
		if err != nil {
			return err
		}
		this.HonsyokinBefore = append(this.HonsyokinBefore, tmp134)
	}
	for i := 0; i < int(5); i++ {
		_ = i
		tmp135, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp135 = tmp135
		tmp136, err := kaitai.BytesToStr(tmp135, japanese.ShiftJIS.NewDecoder())
		if err != nil {
			return err
		}
		this.Fukasyokin = append(this.Fukasyokin, tmp136)
	}
	for i := 0; i < int(3); i++ {
		_ = i
		tmp137, err := this._io.ReadBytes(int(8))
		if err != nil {
			return err
		}
		tmp137 = tmp137
		tmp138, err := kaitai.BytesToStr(tmp137, japanese.ShiftJIS.NewDecoder())
		if err != nil {
			return err
		}
		this.FukasyokinBefore = append(this.FukasyokinBefore, tmp138)
	}
	tmp139, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp139 = tmp139
	tmp140, err := kaitai.BytesToStr(tmp139, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HassoTime = tmp140
	tmp141, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp141 = tmp141
	tmp142, err := kaitai.BytesToStr(tmp141, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.HassoTimeBefore = tmp142
	tmp143, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp143 = tmp143
	tmp144, err := kaitai.BytesToStr(tmp143, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.TorokuTosu = tmp144
	tmp145, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp145 = tmp145
	tmp146, err := kaitai.BytesToStr(tmp145, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.SyussoTosu = tmp146
	tmp147, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp147 = tmp147
	tmp148, err := kaitai.BytesToStr(tmp147, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.NyusenTosu = tmp148
	tmp149, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp149 = tmp149
	tmp150, err := kaitai.BytesToStr(tmp149, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.TenkoCode = tmp150
	tmp151, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp151 = tmp151
	tmp152, err := kaitai.BytesToStr(tmp151, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.SibaBabaCode = tmp152
	tmp153, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp153 = tmp153
	tmp154, err := kaitai.BytesToStr(tmp153, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.DirtBabaCode = tmp154
	tmp155, err := this.IsResult()
	if err != nil {
		return err
	}
	if (tmp155) {
		tmp156 := NewJvRaRace_Result()
		err = tmp156.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Result = tmp156
	}
	return err
}
func (this *JvRaRace_Record) IsResult() (v bool, err error) {
	if (this._f_isResult) {
		return this.isResult, nil
	}
	tmp157, err := strconv.ParseInt(this.DataKubun, 10, 0)
	if err != nil {
		return false, err
	}
	tmp158, err := strconv.ParseInt(this.DataKubun, 10, 0)
	if err != nil {
		return false, err
	}
	this.isResult = bool( ((tmp157 > 2) && (tmp158 < 8)) )
	this._f_isResult = true
	return this.isResult, nil
}
func (this *JvRaRace_Record) Kyori() (v int, err error) {
	if (this._f_kyori) {
		return this.kyori, nil
	}
	tmp159, err := strconv.ParseInt(this.KyoriStr, 10, 0)
	if err != nil {
		return 0, err
	}
	this.kyori = int(tmp159)
	this._f_kyori = true
	return this.kyori, nil
}
func (this *JvRaRace_Record) KyoriBefore() (v int, err error) {
	if (this._f_kyoriBefore) {
		return this.kyoriBefore, nil
	}
	tmp160, err := strconv.ParseInt(this.KyoriBeforeStr, 10, 0)
	if err != nil {
		return 0, err
	}
	this.kyoriBefore = int(tmp160)
	this._f_kyoriBefore = true
	return this.kyoriBefore, nil
}
